# Generated by Django 3.1.2 on 2020-10-29 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('label', models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=2, null=True)),
                ('slug', models.SlugField()),
                ('img_product', models.ImageField(blank=True, null=True, upload_to='')),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_basic.category')),
            ],
        ),
    ]
