# Generated by Django 3.1.2 on 2020-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techshop', '0002_auto_20201022_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='item_id_1'),
            preserve_default=False,
        ),
    ]
