# Generated by Django 3.1.2 on 2020-10-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techshop', '0003_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
