# Generated by Django 3.1.2 on 2020-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techshop', '0004_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='id_item'),
            preserve_default=False,
        ),
    ]
