# Generated by Django 3.1.2 on 2020-10-26 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techshop', '0010_billingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='default',
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='techshop.billingaddress'),
        ),
    ]
