# Generated by Django 3.1.2 on 2020-10-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techshop', '0012_item_img_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Iphone', 'Iphone'), ('Sam Sung', 'Sam Sung'), ('Oppo', 'Oppo'), ('Xiao Mi', 'Xiao Mi')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=2, null=True),
        ),
    ]
