# Generated by Django 3.1.2 on 2020-10-27 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techshop', '0014_auto_20201027_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='item_catagory',
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='techshop.category'),
        ),
    ]
